name: Development Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Setup Java (JVM)
      - name: Setup Java 18
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 18

      # 3. Setup Scala + sbt
      - name: Setup Scala & sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      # 4. Build (compile & stage)
      - name: Build Play Framework App
        run: sbt stage

      # 5. Run Scalastyle (Static Code Analysis)
      - name: Run Scalastyle
#        continue-on-error: true
        run: sbt scalastyle

      # 6. Run tests with coverage
      - name: Run Scoverage Tests
#        continue-on-error: true
        run: sbt clean coverage test coverageReport coverageAggregate